version: '3.3'

services:

  meow-john:
    container_name: meow-john
    build:
      context: ./services/meow
      dockerfile: Dockerfile-dev
    volumes:
      - './services/meow:/usr/src/app'
      - './services/meow/package.json:/usr/src/app/package.json'
      - './services/meow/gulpfile.js:/usr/src/app/gulpfile.js'
    ports:
      - '3003:3000'
    environment:
      - NODE_ENV=development

  meow-paul:
    container_name: meow-paul
    build:
      context: ./services/meow
      dockerfile: Dockerfile-dev
    volumes:
      - './services/meow:/usr/src/app'
      - './services/meow/package.json:/usr/src/app/package.json'
      - './services/meow/gulpfile.js:/usr/src/app/gulpfile.js'
    ports:
      - '3004:3000'
    environment:
      - NODE_ENV=development

  meow-george:
    container_name: meow-george
    build:
      context: ./services/meow
      dockerfile: Dockerfile-dev
    volumes:
      - './services/meow:/usr/src/app'
      - './services/meow/package.json:/usr/src/app/package.json'
      - './services/meow/gulpfile.js:/usr/src/app/gulpfile.js'
    ports:
      - '3005:3000'
    environment:
      - NODE_ENV=development

  meow-ringo:
    container_name: meow-ringo
    build:
      context: ./services/meow
      dockerfile: Dockerfile-dev
    volumes:
      - './services/meow:/usr/src/app'
      - './services/meow/package.json:/usr/src/app/package.json'
      - './services/meow/gulpfile.js:/usr/src/app/gulpfile.js'
    ports:
      - '3006:3000'
    environment:
      - NODE_ENV=development

  client:
    container_name: meow-client
    build:
      context: ./services/client
      dockerfile: Dockerfile-dev
    volumes:
      - './services/client:/usr/src/app'
    ports:
      - '3008:3000'
    environment:
      - NODE_ENV=development
      - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
    depends_on:
      - meow-john
      - meow-paul
      - meow-george
      - meow-ringo
    links:
      - meow-john
      - meow-paul
      - meow-george
      - meow-ringo

  nginx:
    container_name: meow-nginx
    build: ./services/nginx
    ports:
      - 80:80
    depends_on:
      - meow-john
      - meow-paul
      - meow-george
      - meow-ringo
      - client
    links:
      - meow-john
      - meow-paul
      - meow-george
      - meow-ringo
      - client
